#!/bin/bash
# Begin LSF Directives
#BSUB -P CSC359
#BSUB -W 1:00
#BSUB -nnodes 1
#BSUB -J proxal-tests
 
# cd $PROJWORK/csc359/michel/ProxAL.jl
cd /ccs/proj/csc359/michel/git/ProxAL.jl
date
module load cuda
RANKS=6
export JULIA_CUDA_VERBOSE=1
export JULIA_DEPOT_PATH=$PROJWORK/csc359/michel/julia_depot
export JULIA_MPI_BINARY=system
jsrun -n $RANKS -r 6 -c 1 -a 1 -g 1 julia --color=no --project ./examples/exatron.jl 360
