#!/bin/bash
# Begin LSF Directives
#BSUB -P CSC359
#BSUB -W 0:30
#BSUB -nnodes 14
#BSUB -J proxal-tests
 
# Point to your JULIA_DEPOT_PATH.
cd $PROJWORK/csc359/$username/ProxAL.jl
date
module load gcc/7.4.0
module load cuda
export JULIA_CUDA_VERBOSE=1
export JULIA_DEPOT_PATH=$PROJWORK/csc359/$username/julia_depot
export JULIA_MPI_BINARY=system
# Look up these parameters in the Summit documentation
jsrun -n 14 -r 1 -c 1 -a 1 -g 1 julia --color=no --project ./test/distributed168.jl
